apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: integreatly-operator-registry
spec:
  image: quay.io/integreatly/operator-registry:v1.0.0
  imagePullPolicy: Always
  sourceType: grpc